name: Тест
on: [push]
jobs:
  linter_hw1:
    name: Линтер HW1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: |
        cd hw1
        flake8 
  tests_for_hw1:
    name: Тесты HW1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==6.2.5
        pip install numpy
    - name: Тесты HW1
      run: |
        cd hw1
        pytest
  linter_hw1:
      name: Линтер HW2
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Python installation
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
      - name: Flake8
        run: |
          cd hw2
          flake8 
    tests_for_hw1:
      name: Тесты HW2
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install pytest==6.2.5
          pip install numpy
      - name: Тесты HW2
        run: |
          cd hw2
          pytest