name: Проверка
on: [push]
jobs:
  preparation:
    name: Установка Python и зависимостей
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
          pip install pytest==6.2.5
  hw1:
    name: Домашняя работа №1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Flake8
      run: flake8 hw1.py test_hw1.py
    - name: Pytest
      run: pytest test_hw1.py
